FROM debian:jessie

MAINTAINER The Crossbar.io Project <support@crossbario.com>

ENV PYPY_VERSION 5.7.1
ENV PYPY_SHA256SUM 2abaa54d88c9b70b64c37083e7e430a1d3a8f78f8de92e484a988b7aca1e50a7

ARG CROSSBAR_VERSION
ENV HOME /node
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED 1

# install dependencies and Crossbar.io
RUN    apt-get update \
    && apt-get install -y --no-install-recommends \
               ca-certificates \
               curl \
               expat \
               build-essential \
               libssl-dev \

    # install PyPy3 from upstream tarball
    && set -ex \
    && curl -L --output /tmp/pypy.tar.bz2 https://bitbucket.org/pypy/pypy/downloads/pypy3-v${PYPY_VERSION}-linux64.tar.bz2 \
    && echo "$PYPY_SHA256SUM /tmp/pypy.tar.bz2" | sha256sum -c \
    && tar -xjC /usr/local --strip-components=1 -f /tmp/pypy.tar.bz2 \
    && rm /tmp/pypy.tar.bz2 \
    && curl -L --output /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py \
    && pypy3 /tmp/get-pip.py \
    && rm /tmp/get-pip.py \

    # install Crossbar.io from PyPI
    && pip install --no-cache-dir -U pip \
    && pip install --no-cache-dir crossbar==${CROSSBAR_VERSION} \

    # minimize image
    && apt-get remove -y wget expat build-essential \
    && rm -rf ~/.cache \
    && rm -rf /var/lib/apt/lists/*

# test if everything installed properly
RUN crossbar version

# add our user and group
RUN adduser --system --group --uid 242 --home /node crossbar

# initialize a Crossbar.io node
COPY ./node/ /node/
RUN chown -R crossbar:crossbar /node

# make /node a volume to allow external configuration
VOLUME /node

# set the Crossbar.io node directory as working directory
WORKDIR /node

# run under this user, and expose default port
USER crossbar
EXPOSE 8080 8000

# entrypoint for the Docker image is the Crossbar.io executable
ENTRYPOINT ["crossbar", "start", "--cbdir", "/node/.crossbar"]
