FROM alpine

MAINTAINER The Crossbar.io Project <support@crossbario.com>

ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive
ENV NODE_PATH /usr/lib/node_modules/

RUN apk add --update nodejs

# install AutobahnJS globally from https://www.npmjs.com/package/autobahn
RUN npm install -g autobahn

# add an example client
ADD client.js /root/client.js

CMD ["node"]
